language: python

env:
  - PYTHON=2.7

before_install:
  - sudo apt-get update -yq
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH

install:
  - conda update conda --yes
  - conda create --name testenv --yes pip matplotlib numpy nose python=$PYTHON
  - source activate testenv
  - conda install -c https://conda.binstar.org/rsignell pyproj --yes
  - cd external/nn
  - ./configure
  - sudo make install
  - cd ../csa
  - ./configure
  - sudo make install
  - cd ../gridutils
  - ./configure
  - sed -i 's/CFLAGS = -g -O2 -Wall -pedantic/CFLAGS = -g -O2 -Wall -pedantic -fPIC/g' makefile
  - sudo make install
  - cd ../gridgen
  - ./configure
  - sudo make
  - sudo make lib
  - sudo make shlib
  - sudo make install
  - cd ../..
  - pip install .


before_script:
  - ls -al /usr/local/lib
  - ls -al /usr/local/include

script:
  nosetests
